In [34]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [35]:
cm1 = pd.read_csv(r'/content/cm1_csv(1).csv')
print('cm1 shape: ', cm1.shape)
cm1.head()


cm1 shape:  (498, 22)


loc  v(g)  ev(g)  iv(g)     n       v     l      d      i        e  ...  \
0   1.1   1.4    1.4    1.4   1.3    1.30  1.30   1.30   1.30     1.30  ...   
1   1.0   1.0    1.0    1.0   1.0    1.00  1.00   1.00   1.00     1.00  ...   
2  24.0   5.0    1.0    3.0  63.0  309.13  0.11   9.50  32.54  2936.77  ...   
3  20.0   4.0    4.0    2.0  47.0  215.49  0.06  16.00  13.47  3447.89  ...   
4  24.0   6.0    6.0    2.0  72.0  346.13  0.06  17.33  19.97  5999.58  ...   

   lOCode  lOComment  lOBlank  locCodeAndComment  uniq_Op  uniq_Opnd  \
0       2          2        2                  2      1.2        1.2   
1       1          1        1                  1      1.0        1.0   
2       1          0        6                  0     15.0       15.0   
3       0          0        3                  0     16.0        8.0   
4       0          0        3                  0     16.0       12.0   

   total_Op  total_Opnd  branchCount  defects  
0       1.2         1.2          1.4        0  
1       1.0         1.0          1.0        1  
2      44.0        19.0          9.0        0  
3      31.0        16.0          7.0        0  
4      46.0        26.0         11.0        0  

[5 rows x 22 columns]

In [36]:
cm1.info()
cm1.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 498 entries, 0 to 497
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   loc                498 non-null    float64
 1   v(g)               498 non-null    float64
 2   ev(g)              498 non-null    float64
 3   iv(g)              498 non-null    float64
 4   n                  498 non-null    float64
 5   v                  498 non-null    float64
 6   l                  498 non-null    float64
 7   d                  498 non-null    float64
 8   i                  498 non-null    float64
 9   e                  498 non-null    float64
 10  b                  498 non-null    float64
 11  t                  498 non-null    float64
 12  lOCode             498 non-null    int64  
 13  lOComment          498 non-null    int64  
 14  lOBlank            498 non-null    int64  
 15  locCodeAndComment  498 non-null    int64  
 16  uniq_Op            498 non

(498, 22)

In [37]:
y=cm1.iloc[:, 21]
y.head()

0    0
1    1
2    0
3    0
4    0
Name: defects, dtype: int64

In [38]:
#target = 'problems'

x=cm1.drop(['defects'], axis=1)
x.shape
x.head()

loc  v(g)  ev(g)  iv(g)     n       v     l      d      i        e  ...  \
0   1.1   1.4    1.4    1.4   1.3    1.30  1.30   1.30   1.30     1.30  ...   
1   1.0   1.0    1.0    1.0   1.0    1.00  1.00   1.00   1.00     1.00  ...   
2  24.0   5.0    1.0    3.0  63.0  309.13  0.11   9.50  32.54  2936.77  ...   
3  20.0   4.0    4.0    2.0  47.0  215.49  0.06  16.00  13.47  3447.89  ...   
4  24.0   6.0    6.0    2.0  72.0  346.13  0.06  17.33  19.97  5999.58  ...   

        t  lOCode  lOComment  lOBlank  locCodeAndComment  uniq_Op  uniq_Opnd  \
0    1.30       2          2        2                  2      1.2        1.2   
1    1.00       1          1        1                  1      1.0        1.0   
2  163.15       1          0        6                  0     15.0       15.0   
3  191.55       0          0        3                  0     16.0        8.0   
4  333.31       0          0        3                  0     16.0       12.0   

   total_Op  total_Opnd  branchCount  
0       1.2         1.2          1.4  
1       1.0         1.0          1.0  
2      44.0        19.0          9.0  
3      31.0        16.0          7.0  
4      46.0        26.0         11.0  

[5 rows x 21 columns]

In [39]:
y.shape

(498,)

In [40]:
x.shape

(498, 21)

In [41]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import SelectFromModel

In [42]:
logistic = LogisticRegression(C=1, penalty="l1", solver='liblinear', random_state=7).fit(x, y)
model = SelectFromModel(logistic, prefit=True)

In [43]:
x_reduced = model.transform(x)
x_reduced.shape

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but SelectFromModel was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"


(498, 18)

In [44]:
y.shape

(498,)

In [45]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_reduced, y, test_size=0.2, random_state=42, shuffle=True)

In [46]:
print(x.shape)
print(y.shape)
print('-------------------')
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)
np.unique(y_train)
#np.unique(x_train) 

(498, 21)
(498,)
-------------------
(398, 18)
(398,)
(100, 18)
(100,)


array([0, 1])

In [47]:
from sklearn.svm import SVC
from sklearn import metrics #for checking the model accuracy
svc = SVC()

svc.fit(x_train, y_train)
svc_pred=svc.predict(x_test)

In [48]:
from sklearn import metrics #for checking the model accuracy
acc_svm = metrics.accuracy_score(svc_pred,y_test)
print('The accuracy of the SVM is:',acc_svm)
print('Th confusion matrix of SVM:\n ',metrics.confusion_matrix(y_test, svc_pred))

The accuracy of the SVM is: 0.88
Th confusion matrix of SVM:
  [[88  0]
 [12  0]]


In [49]:
print(metrics.confusion_matrix(y_test, svc_pred))
print(metrics.classification_report(y_test, svc_pred))

[[88  0]
 [12  0]]
              precision    recall  f1-score   support

           0       0.88      1.00      0.94        88
           1       0.00      0.00      0.00        12

    accuracy                           0.88       100
   macro avg       0.44      0.50      0.47       100
weighted avg       0.77      0.88      0.82       100



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [50]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=2) #put 2 neighbors because we have 2 labels.
knn.fit(x_train,y_train)
knn_pred = knn.predict(x_test)

In [51]:
acc_knn = metrics.accuracy_score(knn_pred,y_test)
print('The accuracy of the KNN is', acc_knn)
print('The confusion matrix of KNN:\n ',metrics.confusion_matrix(y_test, knn_pred))

The accuracy of the KNN is 0.87
The confusion matrix of KNN:
  [[87  1]
 [12  0]]


In [52]:
print(metrics.confusion_matrix(y_test, knn_pred))
print(metrics.classification_report(y_test, knn_pred))

[[87  1]
 [12  0]]
              precision    recall  f1-score   support

           0       0.88      0.99      0.93        88
           1       0.00      0.00      0.00        12

    accuracy                           0.87       100
   macro avg       0.44      0.49      0.47       100
weighted avg       0.77      0.87      0.82       100



In [53]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(x_train, y_train)
y_predict = model.predict(x_test)
model_score = model.score(x_test, y_test)
print(model_score)
print(metrics.confusion_matrix(y_test, y_predict))
print(metrics.classification_report(y_test, y_predict))

0.82
[[78 10]
 [ 8  4]]
              precision    recall  f1-score   support

           0       0.91      0.89      0.90        88
           1       0.29      0.33      0.31        12

    accuracy                           0.82       100
   macro avg       0.60      0.61      0.60       100
weighted avg       0.83      0.82      0.83       100



In [54]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(x_train, y_train)

GaussianNB()

In [55]:
model.score(x_train, y_train) 

0.8567839195979899

In [56]:
test_pred = model.predict(x_test)
print(metrics.classification_report(y_test, test_pred))
print(metrics.confusion_matrix(y_test, test_pred))

              precision    recall  f1-score   support

           0       0.90      0.98      0.93        88
           1       0.50      0.17      0.25        12

    accuracy                           0.88       100
   macro avg       0.70      0.57      0.59       100
weighted avg       0.85      0.88      0.85       100

[[86  2]
 [10  2]]
