In [15]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [16]:
jm1 = pd.read_csv(r'/content/jm1_csv.csv')
jm1=jm1.replace('?',0)
print('jm1 shape: ', jm1.shape)
jm1.head()

jm1 shape:  (10885, 22)


loc  v(g)  ev(g)  iv(g)      n        v     l      d       i         e  \
0    1.1   1.4    1.4    1.4    1.3     1.30  1.30   1.30    1.30      1.30   
1    1.0   1.0    1.0    1.0    1.0     1.00  1.00   1.00    1.00      1.00   
2   72.0   7.0    1.0    6.0  198.0  1134.13  0.05  20.31   55.85  23029.10   
3  190.0   3.0    1.0    3.0  600.0  4348.76  0.06  17.06  254.87  74202.67   
4   37.0   4.0    1.0    4.0  126.0   599.12  0.06  17.19   34.86  10297.30   

   ...  lOCode  lOComment  lOBlank  locCodeAndComment  uniq_Op  uniq_Opnd  \
0  ...       2          2        2                  2      1.2        1.2   
1  ...       1          1        1                  1        1          1   
2  ...      51         10        8                  1       17         36   
3  ...     129         29       28                  2       17        135   
4  ...      28          1        6                  0       11         16   

  total_Op total_Opnd branchCount defects  
0      1.2        1.2         1.4   False  
1        1          1           1    True  
2      112         86          13    True  
3      329        271           5    True  
4       76         50           7    True  

[5 rows x 22 columns]

In [17]:
jm1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10885 entries, 0 to 10884
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   loc                10885 non-null  float64
 1   v(g)               10885 non-null  float64
 2   ev(g)              10885 non-null  float64
 3   iv(g)              10885 non-null  float64
 4   n                  10885 non-null  float64
 5   v                  10885 non-null  float64
 6   l                  10885 non-null  float64
 7   d                  10885 non-null  float64
 8   i                  10885 non-null  float64
 9   e                  10885 non-null  float64
 10  b                  10885 non-null  float64
 11  t                  10885 non-null  float64
 12  lOCode             10885 non-null  int64  
 13  lOComment          10885 non-null  int64  
 14  lOBlank            10885 non-null  int64  
 15  locCodeAndComment  10885 non-null  int64  
 16  uniq_Op            108

In [18]:
target = 'defects'
y = jm1[target]
x=jm1.drop(['defects'], axis=1)
x.shape

(10885, 21)

In [19]:
y.shape

(10885,)

In [20]:
#x.corr()
#x.corr(method='pearson',min_periods=0)
def correlation(dataset, threshold):
    col_corr = set()  # Set of all the names of correlated columns
    corr_matrix = dataset.corr()
    for i in range(len(corr_matrix.columns)):
        for j in range(i):
            if (corr_matrix.iloc[i, j]) > threshold: # we are interested in absolute coeff value
             #if we want to conseder -ve corelation to be treated as +ve just add abs just after if in above statement like:-
             # if abs(corr_matrix.iloc[i, j]) > threshold:
                colname = corr_matrix.columns[i]  # getting the name of column
                col_corr.add(colname)
    return col_corr

In [21]:
corr_features = correlation(x, 0.8) #can change treshold value accordinglly with current values i will be removing 18 highly corelated features
len(set(corr_features))
selector=corr_features
len(set(corr_features))

9

In [22]:
x.shape

(10885, 21)

In [23]:
x.head()

loc  v(g)  ev(g)  iv(g)      n        v     l      d       i         e  \
0    1.1   1.4    1.4    1.4    1.3     1.30  1.30   1.30    1.30      1.30   
1    1.0   1.0    1.0    1.0    1.0     1.00  1.00   1.00    1.00      1.00   
2   72.0   7.0    1.0    6.0  198.0  1134.13  0.05  20.31   55.85  23029.10   
3  190.0   3.0    1.0    3.0  600.0  4348.76  0.06  17.06  254.87  74202.67   
4   37.0   4.0    1.0    4.0  126.0   599.12  0.06  17.19   34.86  10297.30   

   ...        t  lOCode  lOComment  lOBlank  locCodeAndComment  uniq_Op  \
0  ...     1.30       2          2        2                  2      1.2   
1  ...     1.00       1          1        1                  1        1   
2  ...  1279.39      51         10        8                  1       17   
3  ...  4122.37     129         29       28                  2       17   
4  ...   572.07      28          1        6                  0       11   

  uniq_Opnd total_Op total_Opnd branchCount  
0       1.2      1.2        1.2         1.4  
1         1        1          1           1  
2        36      112         86          13  
3       135      329        271           5  
4        16       76         50           7  

[5 rows x 21 columns]

In [24]:
xn=x.drop(selector,axis=1)

In [25]:
xn.head()

loc  ev(g)     l       i         e  lOComment  locCodeAndComment uniq_Op  \
0    1.1    1.4  1.30    1.30      1.30          2                  2     1.2   
1    1.0    1.0  1.00    1.00      1.00          1                  1       1   
2   72.0    1.0  0.05   55.85  23029.10         10                  1      17   
3  190.0    1.0  0.06  254.87  74202.67         29                  2      17   
4   37.0    1.0  0.06   34.86  10297.30          1                  0      11   

  uniq_Opnd total_Op total_Opnd branchCount  
0       1.2      1.2        1.2         1.4  
1         1        1          1           1  
2        36      112         86          13  
3       135      329        271           5  
4        16       76         50           7

In [26]:
xn.shape

(10885, 12)

In [27]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(xn, y, test_size=0.2, random_state=42, shuffle=True)

In [28]:
print(x.shape)
print(y.shape)
print('-------------------')
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(10885, 21)
(10885,)
-------------------
(8708, 12)
(8708,)
(2177, 12)
(2177,)


In [29]:
from sklearn.svm import SVC
from sklearn import metrics #for checking the model accuracy
svc = SVC()
svc.fit(x_train, y_train)
svc_pred=svc.predict(x_test)
from sklearn import metrics #for checking the model accuracy
acc_svm = metrics.accuracy_score(svc_pred,y_test)
print('The accuracy of the SVM is:',acc_svm)
print('Th confusion matrix of SVM:\n ',metrics.confusion_matrix(y_test, svc_pred))

The accuracy of the SVM is: 0.8066146072576941
Th confusion matrix of SVM:
  [[1749    9]
 [ 412    7]]


In [30]:
print(metrics.confusion_matrix(y_test, svc_pred))
print(metrics.classification_report(y_test, svc_pred))

[[1749    9]
 [ 412    7]]
              precision    recall  f1-score   support

       False       0.81      0.99      0.89      1758
        True       0.44      0.02      0.03       419

    accuracy                           0.81      2177
   macro avg       0.62      0.51      0.46      2177
weighted avg       0.74      0.81      0.73      2177



In [31]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=2) #put 2 neighbors because we have 2 labels.
knn.fit(x_train,y_train)
knn_pred = knn.predict(x_test)
acc_knn = metrics.accuracy_score(knn_pred,y_test)
print('The accuracy of the KNN is', acc_knn)
print('The confusion matrix of KNN:\n ',metrics.confusion_matrix(y_test, knn_pred))
print(metrics.confusion_matrix(y_test, knn_pred))
print(metrics.classification_report(y_test, knn_pred))

The accuracy of the KNN is 0.7951309141019752
The confusion matrix of KNN:
  [[1683   75]
 [ 371   48]]
[[1683   75]
 [ 371   48]]
              precision    recall  f1-score   support

       False       0.82      0.96      0.88      1758
        True       0.39      0.11      0.18       419

    accuracy                           0.80      2177
   macro avg       0.60      0.54      0.53      2177
weighted avg       0.74      0.80      0.75      2177



In [32]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(x_train, y_train)
y_predict = model.predict(x_test)
model_score = model.score(x_test, y_test)
print(model_score)
print(metrics.confusion_matrix(y_test, y_predict))
print(metrics.classification_report(y_test, y_predict))

0.7459807073954984
[[1473  285]
 [ 268  151]]
              precision    recall  f1-score   support

       False       0.85      0.84      0.84      1758
        True       0.35      0.36      0.35       419

    accuracy                           0.75      2177
   macro avg       0.60      0.60      0.60      2177
weighted avg       0.75      0.75      0.75      2177



In [33]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(x_train, y_train)
model.score(x_train, y_train) 

0.8052365640790078

In [34]:
test_pred = model.predict(x_test)
print(metrics.classification_report(y_test, test_pred))
print(metrics.confusion_matrix(y_test, test_pred))

              precision    recall  f1-score   support

       False       0.83      0.97      0.89      1758
        True       0.50      0.15      0.23       419

    accuracy                           0.81      2177
   macro avg       0.66      0.56      0.56      2177
weighted avg       0.76      0.81      0.76      2177

[[1697   61]
 [ 358   61]]
